# Generated by Django 5.1.5 on 2025-02-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_user_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_style",
            field=models.CharField(max_length=1000),
        ),
    ]
