# Generated by Django 5.1.5 on 2025-02-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_user_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
    ]
